### ISSUE TITLE
Error showing in code

### ISSUE THREAD

**Issue by rajraman786** [0xlittleboy/SubDomz#10]
After installing when I tried to use it shows a syntax error in line 144.
attaching SS for reference.

![Screenshot from 2022-11-04 15-48-24](https://user-images.githubusercontent.com/55931033/199949398-054ff1c7-b397-42f9-a2df-6e2b1fc85877.png)

**Comment by 0xlittleboy** [comment]
Add your GitHub token in line 144
Check this,
https://github.com/0xlittleboy/SubDomz/#api-keys

**Comment by rajraman786** [comment]
oh got it.
Thanks btw.
