### ISSUE TITLE
./install.sh: line 144: cd: /home/kali/SubDomz/tools: No such file or directory

### ISSUE THREAD

**Issue by black-arch7** [0xlittleboy/SubDomz#5]
./install.sh: line 144: cd: /home/kali/SubDomz/tools: No such file or directory
./install.sh: line 176: cd: /home/kali/SubDomz/tools: No such file or directory

and after installation tools folder is empty there were no file...please help to fiz and always getting stuked at amass searching

**Comment by 0xlittleboy** [comment]
@black-arch7 
1. If you these tools are already installed in your system, it doesn't shows in tools directory.
2. Amass is bit slow by default so it tooks a lot of time to finish. You can use ``-p`` flag for faster results.
